### PR TITLE
update to 24

### PR DESCRIPTION
**Pull request by xgp**

### CODE REVIEW

**Comment by xgp** [comment]
For some reason, the `datastore` isn't loading:
```
Caused by: java.lang.RuntimeException: Failed to find provider legacy for datastore
	at org.keycloak.services.DefaultKeycloakSessionFactory.checkProvider(DefaultKeycloakSessionFactory.java:233)
	at org.keycloak.services.DefaultKeycloakSessionFactory.init(DefaultKeycloakSessionFactory.java:119)
	at io.phasetwo.keycloak.jpacache.testsuite.KeycloakModelTest$4.init(KeycloakModelTest.java:318)
	at io.phasetwo.keycloak.jpacache.testsuite.KeycloakModelTest.createKeycloakSessionFactory(KeycloakModelTest.java:346)
	at io.phasetwo.keycloak.jpacache.testsuite.KeycloakModelTest.reinitializeKeycloakSessionFactory(KeycloakModelTest.java:357)
	at io.phasetwo.keycloak.jpacache.testsuite.KeycloakModelTest.<clinit>(KeycloakModelTest.java:289)
	... 50 more
```

**Comment by xgp** [comment]
For some reason, the `datastore` isn't loading:
```
Caused by: java.lang.RuntimeException: Failed to find provider legacy for datastore
	at org.keycloak.services.DefaultKeycloakSessionFactory.checkProvider(DefaultKeycloakSessionFactory.java:233)
	at org.keycloak.services.DefaultKeycloakSessionFactory.init(DefaultKeycloakSessionFactory.java:119)
	at io.phasetwo.keycloak.jpacache.testsuite.KeycloakModelTest$4.init(KeycloakModelTest.java:318)
	at io.phasetwo.keycloak.jpacache.testsuite.KeycloakModelTest.createKeycloakSessionFactory(KeycloakModelTest.java:346)
	at io.phasetwo.keycloak.jpacache.testsuite.KeycloakModelTest.reinitializeKeycloakSessionFactory(KeycloakModelTest.java:357)
	at io.phasetwo.keycloak.jpacache.testsuite.KeycloakModelTest.<clinit>(KeycloakModelTest.java:289)
	... 50 more
```

FYI @rtufisi this is my port to Keycloak `24`. The tests are failing because the datastore won't load. If you have time, please look at this.

**Comment by rtufisi** [comment]
Hei Garth, could you please try again with the latest changes? The datastore was removed

**Comment by xgp** [comment]
@rtufisi This is my branch to upgrade to Keycloak `24`. There are a lot of changes, but they are mostly structural. Please look around a see if you can understand why the tests are failing.

**Comment by rtufisi** [comment]
I will take a look

**Pull request merged**
